<a href="https://colab.research.google.com/github/pksheaad/pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PYTORCH Basic Fundamental

In [6]:
import torch
from torch import nn #// nn contains all building block of neural network
from matplotlib.pyplot import plot
import numpy as np


torch.__version__

'2.8.0+cu126'

### Initializing and basic operations

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [7]:
vector = torch.tensor([[1.,-1.],[1.,-1.]])
vector

tensor([[ 1., -1.],
        [ 1., -1.]])

In [8]:
torch.tensor(np.array(vector))

tensor([[ 1., -1.],
        [ 1., -1.]])

A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [9]:
torch.zeros([2,4], dtype=torch.int32, device="cpu")

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [14]:
#cuda0 = torch.device('cuda:0')
torch.ones([3,5], dtype=torch.float64, device="cpu")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [16]:
x = torch.tensor([[1,5,8],[3,7,9],[4,5,6]])
x
print(x[0])
print(x[1][2])
x[2,2] = 10
x

tensor([1, 5, 8])
tensor(9)


tensor([[ 1,  5,  8],
        [ 3,  7,  9],
        [ 4,  5, 10]])

Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

In [17]:
x = torch.tensor(5)
x
print(x.item())

5


In [18]:
x = torch.tensor(10.00)
print(x)
print(x.item())

tensor(10.)
10.0


In [19]:
scaler = torch.tensor(7)
scaler

tensor(7)

We can check the dimensions of a tensor using the ndim attribute.

In [20]:
scaler.ndim

0

torch.Tensor to a Python integer can we done by item() method

In [21]:
scaler.item()

7

In [22]:
vector = torch.tensor([7.,7])
# dimension of vector
print(vector.ndim)
# shape of vector, Shapes tells us how the elemnt in the vector are arranged
print(vector.shape)

1
torch.Size([2])


In [23]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
# Dimension of MATRIX
print(MATRIX.ndim)

# Shape of MATRIX
print(MATRIX.shape)

# Accessing element of MATRIX
print(MATRIX[0])
print(MATRIX[1,1])

2
torch.Size([3, 3])
tensor([1, 2, 3])
tensor(5)


In [24]:
TENSOR = torch.tensor([[[10,20,30],
                        [40,50,60],
                        [70,80,90]]])

In [26]:
TENSOR
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1][2]) # Ans must be 60

3
torch.Size([1, 3, 3])
tensor(60)
