<a href="https://colab.research.google.com/github/pksheaad/pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PYTORCH Basic Fundamental

In [6]:
import torch
from torch import nn #// nn contains all building block of neural network
from matplotlib.pyplot import plot
import numpy as np


torch.__version__

'2.8.0+cu126'

### Initializing and basic operations

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [7]:
vector = torch.tensor([[1.,-1.],[1.,-1.]])
vector

tensor([[ 1., -1.],
        [ 1., -1.]])

In [8]:
torch.tensor(np.array(vector))

tensor([[ 1., -1.],
        [ 1., -1.]])

A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [9]:
torch.zeros([2,4], dtype=torch.int32, device="cpu")

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [14]:
#cuda0 = torch.device('cuda:0')
torch.ones([3,5], dtype=torch.float64, device="cpu")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [16]:
x = torch.tensor([[1,5,8],[3,7,9],[4,5,6]])
x
print(x[0])
print(x[1][2])
x[2,2] = 10
x

tensor([1, 5, 8])
tensor(9)


tensor([[ 1,  5,  8],
        [ 3,  7,  9],
        [ 4,  5, 10]])

Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

In [17]:
x = torch.tensor(5)
x
print(x.item())

5


In [18]:
x = torch.tensor(10.00)
print(x)
print(x.item())

tensor(10.)
10.0


In [19]:
scaler = torch.tensor(7)
scaler

tensor(7)

We can check the dimensions of a tensor using the ndim attribute.

In [20]:
scaler.ndim

0

torch.Tensor to a Python integer can we done by item() method

In [21]:
scaler.item()

7

In [22]:
vector = torch.tensor([7.,7])
# dimension of vector
print(vector.ndim)
# shape of vector, Shapes tells us how the elemnt in the vector are arranged
print(vector.shape)

1
torch.Size([2])


In [23]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
# Dimension of MATRIX
print(MATRIX.ndim)

# Shape of MATRIX
print(MATRIX.shape)

# Accessing element of MATRIX
print(MATRIX[0])
print(MATRIX[1,1])

2
torch.Size([3, 3])
tensor([1, 2, 3])
tensor(5)


In [24]:
TENSOR = torch.tensor([[[10,20,30],
                        [40,50,60],
                        [70,80,90]]])

In [26]:
TENSOR
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1][2]) # Ans must be 60

3
torch.Size([1, 3, 3])
tensor(60)


#Random tensors

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [32]:
# Creating a random tensor with scaler data
random_tensor = torch.rand(size=(2,))
random_tensor

# Dimension of random_tensor
print(random_tensor.ndim)

# Shape of randmon_tensor

print(random_tensor.shape)


1
torch.Size([2])


In [33]:
# Creating a random tensor with vector data (3,4)
random_tensor_vector = torch.rand(size=(3,4))
print(random_tensor_vector)
# Dimension of random_tensor_vector
print(random_tensor_vector.ndim)
# Shape of a random_tensor_vector
print(random_tensor_vector.shape)

tensor([[0.1520, 0.4504, 0.7371, 0.3086],
        [0.2718, 0.9645, 0.4150, 0.6766],
        [0.3237, 0.0822, 0.7009, 0.3695]])
2
torch.Size([3, 4])


In [34]:
# How to generate an random image size tensor an Image with 3 different color (R,G,B),width=300 and height=300
random_image_size_tensor = torch.rand(3,300,300)
random_image_size_tensor

tensor([[[4.7902e-01, 1.0269e-01, 8.0089e-01,  ..., 5.1597e-01,
          5.9018e-01, 2.4137e-01],
         [1.4037e-02, 3.8217e-02, 3.3968e-01,  ..., 7.1709e-02,
          3.1543e-01, 2.0386e-01],
         [2.2526e-01, 7.1643e-01, 4.2901e-01,  ..., 6.6005e-01,
          9.1887e-01, 6.3718e-01],
         ...,
         [9.5134e-01, 9.0304e-02, 7.6485e-01,  ..., 5.6831e-01,
          9.9956e-01, 2.5145e-01],
         [7.4909e-01, 2.0525e-01, 5.4213e-01,  ..., 4.5902e-01,
          1.3874e-01, 5.6403e-01],
         [9.0098e-01, 5.1240e-01, 3.9638e-02,  ..., 9.0231e-01,
          6.9621e-01, 5.4922e-01]],

        [[3.5371e-01, 1.3834e-01, 2.2533e-01,  ..., 5.7735e-01,
          7.8355e-01, 3.4634e-01],
         [2.5160e-02, 6.3428e-01, 5.5938e-02,  ..., 4.2822e-01,
          6.7005e-01, 3.7916e-01],
         [2.3007e-04, 6.4180e-01, 2.6304e-01,  ..., 2.6655e-01,
          5.4923e-01, 8.8493e-01],
         ...,
         [2.6186e-01, 4.4487e-01, 3.3100e-01,  ..., 8.5920e-01,
          5.035

# Zeros and ones¶

torch.zeros(size=)

torch.ones(size=)

In [35]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros.dtype

torch.float32

In [37]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [ ]:
#