<a href="https://colab.research.google.com/github/pksheaad/pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PYTORCH Basic Fundamental

In [1]:
import torch
from torch import nn #// nn contains all building block of neural network
from matplotlib.pyplot import plot
import numpy as np


torch.__version__

'2.8.0+cu126'

### Initializing and basic operations

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [2]:
vector = torch.tensor([[1.,-1.],[1.,-1.]])
vector

tensor([[ 1., -1.],
        [ 1., -1.]])

In [3]:
torch.tensor(np.array(vector))

tensor([[ 1., -1.],
        [ 1., -1.]])

A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [4]:
torch.zeros([2,4], dtype=torch.int32, device="cpu")

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [5]:
#cuda0 = torch.device('cuda:0')
torch.ones([3,5], dtype=torch.float64, device="cpu")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [6]:
x = torch.tensor([[1,5,8],[3,7,9],[4,5,6]])
x
print(x[0])
print(x[1][2])
x[2,2] = 10
x

tensor([1, 5, 8])
tensor(9)


tensor([[ 1,  5,  8],
        [ 3,  7,  9],
        [ 4,  5, 10]])

Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

In [7]:
x = torch.tensor(5)
x
print(x.item())

5


In [8]:
x = torch.tensor(10.00)
print(x)
print(x.item())

tensor(10.)
10.0


In [9]:
scaler = torch.tensor(7)
scaler

tensor(7)

We can check the dimensions of a tensor using the ndim attribute.

In [10]:
scaler.ndim

0

torch.Tensor to a Python integer can we done by item() method

In [11]:
scaler.item()

7

In [12]:
vector = torch.tensor([7.,7])
# dimension of vector
print(vector.ndim)
# shape of vector, Shapes tells us how the elemnt in the vector are arranged
print(vector.shape)

1
torch.Size([2])


In [13]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
# Dimension of MATRIX
print(MATRIX.ndim)

# Shape of MATRIX
print(MATRIX.shape)

# Accessing element of MATRIX
print(MATRIX[0])
print(MATRIX[1,1])

2
torch.Size([3, 3])
tensor([1, 2, 3])
tensor(5)


In [14]:
TENSOR = torch.tensor([[[10,20,30],
                        [40,50,60],
                        [70,80,90]]])

In [15]:
TENSOR
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1][2]) # Ans must be 60

3
torch.Size([1, 3, 3])
tensor(60)


#Random tensors

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [16]:
# Creating a random tensor with scaler data
random_tensor = torch.rand(size=(2,))
random_tensor

# Dimension of random_tensor
print(random_tensor.ndim)

# Shape of randmon_tensor

print(random_tensor.shape)


1
torch.Size([2])


In [17]:
# Creating a random tensor with vector data (3,4)
random_tensor_vector = torch.rand(size=(3,4))
print(random_tensor_vector)
# Dimension of random_tensor_vector
print(random_tensor_vector.ndim)
# Shape of a random_tensor_vector
print(random_tensor_vector.shape)

tensor([[0.2428, 0.5849, 0.4184, 0.9686],
        [0.2259, 0.3050, 0.0587, 0.0511],
        [0.5410, 0.3524, 0.4848, 0.0901]])
2
torch.Size([3, 4])


In [18]:
# How to generate an random image size tensor an Image with 3 different color (R,G,B),width=300 and height=300
random_image_size_tensor = torch.rand(3,300,300)
random_image_size_tensor

tensor([[[0.4555, 0.7060, 0.7650,  ..., 0.6060, 0.4679, 0.9493],
         [0.3311, 0.2082, 0.0219,  ..., 0.1670, 0.2633, 0.4776],
         [0.5939, 0.2315, 0.0450,  ..., 0.5946, 0.1515, 0.0864],
         ...,
         [0.8091, 0.5833, 0.4223,  ..., 0.4066, 0.3922, 0.7268],
         [0.8898, 0.8970, 0.9407,  ..., 0.6729, 0.4734, 0.9505],
         [0.5282, 0.9668, 0.0516,  ..., 0.6637, 0.0760, 0.4203]],

        [[0.3121, 0.0093, 0.6483,  ..., 0.9185, 0.3403, 0.3906],
         [0.6913, 0.0241, 0.8303,  ..., 0.9499, 0.2075, 0.9036],
         [0.1264, 0.7459, 0.4222,  ..., 0.8306, 0.7336, 0.7782],
         ...,
         [0.2145, 0.5676, 0.1735,  ..., 0.3386, 0.7469, 0.5688],
         [0.3592, 0.2770, 0.8195,  ..., 0.5998, 0.2583, 0.3823],
         [0.2476, 0.2768, 0.1024,  ..., 0.9230, 0.4059, 0.1163]],

        [[0.9647, 0.0135, 0.3583,  ..., 0.1792, 0.0177, 0.1600],
         [0.2413, 0.3027, 0.2711,  ..., 0.3839, 0.2546, 0.7095],
         [0.9939, 0.7288, 0.8587,  ..., 0.4744, 0.1391, 0.

# Zeros and ones¶

torch.zeros(size=)

torch.ones(size=)

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros.dtype

torch.float32

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

# Creating Range and Like Tensor

In [25]:
# arange method will be used arange(start=, end=, step=)
one_to_thousands = torch.arange(start = 0, end=1001, step=100)
one_to_thousands

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [26]:
# Creatng Like tensor use like(input) method
tens_zeros = torch.zeros_like(one_to_thousands)
tens_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
one_to_ten = torch.arange(0,10,1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Data Type in Tensor

### Deafult datatype is float32,

####Basically three issue we faced while computing in Torch in Deep Learning
1. Operation is not same data type Tensor
2. Operation on two different shape Tensor
3. Operation on two different Tensor running on different devices.

In [31]:
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None,  # default float32, explicitly define tensor datatype
                        device=None, # default cpu explicitly define device type
                        requires_grad=False) # If True operation performed on Tensor recorded
float_32

tensor([3., 6., 9.])

In [32]:
float_32.dtype

torch.float32

In [36]:
float_16_tensor = float_32.type(torch.float16)

In [37]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
int_8_tensor = torch.tensor([1,2,3],dtype=torch.int8)
int_8_tensor

tensor([1, 2, 3], dtype=torch.int8)

# Getting Attribute of Tensor

1. Getting Datatype of Tensor use tensor.dtype
2. Getting Shape of Tensor use tensor.shape
3. Getting device of Tensor use tensor.device

In [39]:
some_rand_tensor = torch.rand(size = (3,4), dtype=torch.float64)
print(some_rand_tensor)
print("Data type of Tensor is {}".format(some_rand_tensor.dtype))
print("Shape of Tensor is {}".format(some_rand_tensor.shape))
print("Device is used for Tensor {}".format(some_rand_tensor.device))

tensor([[0.2941, 0.3483, 0.0720, 0.7606],
        [0.7014, 0.7091, 0.7477, 0.0879],
        [0.8076, 0.9868, 0.6959, 0.6606]], dtype=torch.float64)
Data type of Tensor is torch.float64
Shape of Tensor is torch.Size([3, 4])
Device is used for Tensor cpu


# Manipulation Tensor (Operation on Tensor)
1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [40]:
tensor = torch.rand(size = (2,2), dtype=torch.float16)
tensor

tensor([[0.8892, 0.7227],
        [0.9526, 0.6763]], dtype=torch.float16)

In [41]:
# Addition of 10 in tensor
print("Addition of 10 {}".format(tensor+10))
# Substartion of 10
print("Subtraction of 10 {}".format(tensor-10))
# Multiplication of 10
print("Multiplication of 10 {}".format(tensor*10))
# Division of 10
print("Division of 10 {}".format(tensor/10))

Addition of 10 tensor([[10.8906, 10.7188],
        [10.9531, 10.6797]], dtype=torch.float16)
Subtraction of 10 tensor([[-9.1094, -9.2812],
        [-9.0469, -9.3203]], dtype=torch.float16)
Multiplication of 10 tensor([[8.8906, 7.2266],
        [9.5234, 6.7617]], dtype=torch.float16)
Division of 10 tensor([[0.0889, 0.0723],
        [0.0953, 0.0676]], dtype=torch.float16)


# Matrix Multiplcation

Q = [1,2,3]
1. Element-wise multiplication	[1 * 1, 2 * 2, 3 * 3] = [1, 4, 9]	tensor * tensor
2. Matrix multiplication	[1 * 1 + 2 * 2 + 3 * 3] = [14]	tensor.matmul(tensor)

In [43]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [45]:
# ELement wise multiplication

print (" tensor * tensor = {}".format(tensor*tensor))

 tensor * tensor = tensor([1, 4, 9])


In [47]:
# dot multiplaction
print("Dot Multiplication = {}".format(tensor.matmul(tensor)) )

Dot Multiplication = 14


In [52]:
MATRIX_1 = torch.tensor([[1,2,3],
                         [4,5,6]])
MATRIX_1.shape

torch.Size([2, 3])

In [54]:
MATRIX_2 = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
MATRIX_2.shape

torch.Size([3, 2])

In [55]:
# Matrix Multiplcation
MAT_PRODUCT = MATRIX_1.matmul(MATRIX_2)
MAT_PRODUCT

tensor([[ 58,  64],
        [139, 154]])

In [23]:
#