<a href="https://colab.research.google.com/github/pksheaad/pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PYTORCH Basic Fundamental

In [ ]:
import torch
from torch import nn #// nn contains all building block of neural network
from matplotlib.pyplot import plot
import numpy as np


torch.__version__

'2.8.0+cu126'

### Initializing and basic operations

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [ ]:
vector = torch.tensor([[1.,-1.],[1.,-1.]])
vector

tensor([[ 1., -1.],
        [ 1., -1.]])

In [ ]:
torch.tensor(np.array(vector))

tensor([[ 1., -1.],
        [ 1., -1.]])

A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [ ]:
torch.zeros([2,4], dtype=torch.int32, device="cpu")

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
#cuda0 = torch.device('cuda:0')
torch.ones([3,5], dtype=torch.float64, device="cpu")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [ ]:
x = torch.tensor([[1,5,8],[3,7,9],[4,5,6]])
x
print(x[0])
print(x[1][2])
x[2,2] = 10
x

tensor([1, 5, 8])
tensor(9)


tensor([[ 1,  5,  8],
        [ 3,  7,  9],
        [ 4,  5, 10]])

Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

In [ ]:
x = torch.tensor(10.00)
print(x)
print(x.item())

tensor(10.)
10.0


In [ ]:
x = torch.tensor(5)
x
print(x.item())

5


In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

We can check the dimensions of a tensor using the ndim attribute.

In [ ]:
scaler.ndim

0

torch.Tensor to a Python integer can we done by item() method

In [ ]:
scaler.item()

7

In [ ]:
vector = torch.tensor([7.,7])
# dimension of vector
print(vector.ndim)
# shape of vector, Shapes tells us how the elemnt in the vector are arranged
print(vector.shape)

1
torch.Size([2])


In [ ]:
print(vector[0].tolist())

7.0


In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
# Dimension of MATRIX
print(MATRIX.ndim)

# Shape of MATRIX
print(MATRIX.shape)

# Accessing element of MATRIX
print(MATRIX[0])
print(MATRIX[1,1])
print(MATRIX[0].tolist())

2
torch.Size([3, 3])
tensor([1, 2, 3])
tensor(5)
[1, 2, 3]


In [ ]:
TENSOR = torch.tensor([[[10,20,30],
                        [40,50,60],
                        [70,80,90]]])

In [ ]:
TENSOR
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])
print(TENSOR[0][1][2]) # Ans must be 60

3
torch.Size([1, 3, 3])
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor(60)


#Random tensors

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [ ]:
# Creating a random tensor with scaler data
random_tensor = torch.rand(size=(2,))
random_tensor

# Dimension of random_tensor
print(random_tensor.ndim)

# Shape of randmon_tensor

print(random_tensor.shape)


1
torch.Size([2])


In [ ]:
# Creating a random tensor with vector data (3,4)
random_tensor_vector = torch.rand(size=(3,4))
print(random_tensor_vector)
# Dimension of random_tensor_vector
print(random_tensor_vector.ndim)
# Shape of a random_tensor_vector
print(random_tensor_vector.shape)

tensor([[0.8532, 0.7766, 0.4091, 0.3515],
        [0.3158, 0.1101, 0.8278, 0.1608],
        [0.6361, 0.3724, 0.3625, 0.8084]])
2
torch.Size([3, 4])


In [ ]:
# How to generate an random image size tensor an Image with 3 different color (R,G,B),width=300 and height=300
random_image_size_tensor = torch.rand(3,300,300)
random_image_size_tensor

tensor([[[0.4411, 0.8005, 0.2848,  ..., 0.8066, 0.9327, 0.8552],
         [0.9762, 0.0804, 0.3541,  ..., 0.8657, 0.2090, 0.9843],
         [0.1580, 0.8095, 0.7243,  ..., 0.8347, 0.9687, 0.8193],
         ...,
         [0.3309, 0.5260, 0.3603,  ..., 0.0566, 0.2969, 0.1558],
         [0.6024, 0.2167, 0.2843,  ..., 0.1361, 0.8244, 0.4764],
         [0.5388, 0.9363, 0.0288,  ..., 0.1326, 0.9325, 0.9308]],

        [[0.1120, 0.9589, 0.0037,  ..., 0.2575, 0.9300, 0.3633],
         [0.9988, 0.6440, 0.2392,  ..., 0.7232, 0.5998, 0.2166],
         [0.4114, 0.3388, 0.6764,  ..., 0.3194, 0.8752, 0.4458],
         ...,
         [0.7873, 0.3542, 0.4490,  ..., 0.7023, 0.7174, 0.4871],
         [0.3623, 0.8776, 0.8056,  ..., 0.6355, 0.6796, 0.0982],
         [0.6360, 0.0891, 0.7260,  ..., 0.1884, 0.4641, 0.9414]],

        [[0.8574, 0.9777, 0.4811,  ..., 0.8948, 0.1230, 0.2973],
         [0.9012, 0.8123, 0.2730,  ..., 0.8131, 0.0214, 0.0846],
         [0.2389, 0.0378, 0.0936,  ..., 0.1732, 0.8144, 0.

# Zeros and ones¶

torch.zeros(size=)

torch.ones(size=)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating Range and Like Tensor

In [ ]:
# arange method will be used arange(start=, end=, step=)
one_to_thousands = torch.arange(start = 0, end=1001, step=100)
one_to_thousands

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
# Creatng Like tensor use like(input) method
tens_zeros = torch.zeros_like(one_to_thousands)
tens_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one_to_ten = torch.arange(0,10,1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Data Type in Tensor

### Deafult datatype is float32,

####Basically three issue we faced while computing in Torch in Deep Learning
1. Operation is not same data type Tensor
2. Operation on two different shape Tensor
3. Operation on two different Tensor running on different devices.

In [ ]:
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None,  # default float32, explicitly define tensor datatype
                        device=None, # default cpu explicitly define device type
                        requires_grad=False) # If True operation performed on Tensor recorded
float_32

tensor([3., 6., 9.])

In [ ]:
float_32.dtype

torch.float32

In [ ]:
float_16_tensor = float_32.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_8_tensor = torch.tensor([1,2,3],dtype=torch.int8)
int_8_tensor

tensor([1, 2, 3], dtype=torch.int8)

# Getting Attribute of Tensor

1. Getting Datatype of Tensor use tensor.dtype
2. Getting Shape of Tensor use tensor.shape
3. Getting device of Tensor use tensor.device

In [ ]:
some_rand_tensor = torch.rand(size = (3,4), dtype=torch.float64)
print(some_rand_tensor)
print("Data type of Tensor is {}".format(some_rand_tensor.dtype))
print("Shape of Tensor is {}".format(some_rand_tensor.shape))
print("Device is used for Tensor {}".format(some_rand_tensor.device))

tensor([[0.1673, 0.5690, 0.7608, 0.0195],
        [0.6799, 0.9738, 0.5338, 0.8904],
        [0.8190, 0.5011, 0.1793, 0.5260]], dtype=torch.float64)
Data type of Tensor is torch.float64
Shape of Tensor is torch.Size([3, 4])
Device is used for Tensor cpu


# Manipulation Tensor (Operation on Tensor)
1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [ ]:
tensor = torch.rand(size = (2,2), dtype=torch.float16)
tensor

tensor([[0.8936, 0.6797],
        [0.4175, 0.7026]], dtype=torch.float16)

In [ ]:
# Addition of 10 in tensor
print("Addition of 10 {}".format(tensor+10))
# Substartion of 10
print("Subtraction of 10 {}".format(tensor-10))
# Multiplication of 10
print("Multiplication of 10 {}".format(tensor*10))
# Division of 10
print("Division of 10 {}".format(tensor/10))

Addition of 10 tensor([[10.8906, 10.6797],
        [10.4141, 10.7031]], dtype=torch.float16)
Subtraction of 10 tensor([[-9.1094, -9.3203],
        [-9.5859, -9.2969]], dtype=torch.float16)
Multiplication of 10 tensor([[8.9375, 6.7969],
        [4.1758, 7.0273]], dtype=torch.float16)
Division of 10 tensor([[0.0894, 0.0680],
        [0.0417, 0.0703]], dtype=torch.float16)


# Matrix Multiplcation

Q = [1,2,3]
1. Element-wise multiplication	[1 * 1, 2 * 2, 3 * 3] = [1, 4, 9]	tensor * tensor
2. Matrix multiplication	[1 * 1 + 2 * 2 + 3 * 3] = [14]	tensor.matmul(tensor)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
# ELement wise multiplication

print (" tensor * tensor = {}".format(tensor*tensor))

 tensor * tensor = tensor([1, 4, 9])


In [ ]:
# dot multiplaction
print("Dot Multiplication = {}".format(tensor.matmul(tensor)) )

Dot Multiplication = 14


In [ ]:
MATRIX_1 = torch.tensor([[1,2,3],
                         [4,5,6]])
MATRIX_1.shape

torch.Size([2, 3])

In [ ]:
MATRIX_2 = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
MATRIX_2.shape

torch.Size([3, 2])

In [ ]:
# Matrix Multiplcation
MAT_PRODUCT = MATRIX_1.matmul(MATRIX_2)
MAT_PRODUCT

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])


In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
# Transpsoing the Tensor_B
output = torch.matmul(tensor_A,tensor_B.T)
print(output)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
print(f"Orginal Shape: Tensor_A->{tensor_A.shape}, Tensor_B->{tensor_B.shape}\n")
print(f"New Shape: Tensor_A(Same as above)->{tensor_A.shape}, Tensor_B-> {tensor_B.T}\n")
print(f"Mulatiplying {tensor_A.shape} @ {tensor_B.T}, Inner dimensions match \n")
output = torch.mm(tensor_A,tensor_B.T)
print(f"Output \n")
print(output)
print(f"Shape of output->{output.shape}")

Orginal Shape: Tensor_A->torch.Size([3, 2]), Tensor_B->torch.Size([3, 2])

New Shape: Tensor_A(Same as above)->torch.Size([3, 2]), Tensor_B-> tensor([[ 7,  8,  9],
        [10, 11, 12]])

Mulatiplying torch.Size([3, 2]) @ tensor([[ 7,  8,  9],
        [10, 11, 12]]), Inner dimensions match 

Output 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Shape of output->torch.Size([3, 3])


# Linear
torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
Applies a linear transformation to the incoming data:
$$ y = x\cdot{A^T} + b $$



In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)
#Linear
torch_random_linear = torch.nn.Linear(in_features=10, #in_feature = Define inner dimension of input
                                      out_features=6) # describe outer value
# Creating Matrix 2X3
tensor_A = torch.randn(2,10)
print("Size of tensor_A {}".format(tensor_A.shape))
output = torch_random_linear(tensor_A)
print(" Output \n {}".format(output))
print("Output shape {}".format(output.shape))


Size of tensor_A torch.Size([2, 10])
 Output 
 tensor([[-0.1000,  0.9796, -0.8712,  0.0889,  0.2433, -1.1368],
        [ 0.5277, -0.0021,  0.2297,  1.2705,  1.1197,  0.7797]],
       grad_fn=<AddmmBackward0>)
Output shape torch.Size([2, 6])


# Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# create a tensor

x= torch.arange(start=10, end=1001, step=20)
print(x)
print("Minimum value: = {}".format(x.min()))
print("Maximum value: = {}".format(x.max()))
print("Meanvalue: = {}".format(x.type(dtype=torch.float32).mean())) # Data Type conversion required as mean has float value
print("Sum: {}".format(x.sum()))



tensor([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190, 210, 230, 250, 270,
        290, 310, 330, 350, 370, 390, 410, 430, 450, 470, 490, 510, 530, 550,
        570, 590, 610, 630, 650, 670, 690, 710, 730, 750, 770, 790, 810, 830,
        850, 870, 890, 910, 930, 950, 970, 990])
Minimum value: = 10
Maximum value: = 990
Meanvalue: = 500.0
Sum: 25000


#### We can do the above code with the below method also
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

In [ ]:
x = torch.arange(0,100,5)
print("x:= {}".format(x))
print("Min value is: = {}".format(torch.min(x)))
print("Max value is: = {}".format(torch.max(x)))
print("Mean value is: = {}".format(torch.mean(x.type(dtype=torch.float32))))
print("Sum is: = {}".format(torch.sum(x)))

x:= tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])
Min value is: = 0
Max value is: = 95
Mean value is: = 47.5
Sum is: = 950


# Getting the positional min and max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [ ]:
# creation a tensor
random_tensor = torch.arange(2,79,6)
# printing the tensor
print(random_tensor)
# Getting the max value and position of max value
print("max value: = {} and position of max value: = {}".
      format(torch.max(random_tensor),torch.argmax(random_tensor)))
# Getting the min value and position of min value
print("min value: = {} and position of min value: = {}".
      format(torch.min(random_tensor),torch.argmin(random_tensor)))

tensor([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74])
max value: = 74 and position of max value: = 12
min value: = 2 and position of min value: = 0


# Change tensor datatype

We can change tensor data type by using method torch.tensor.type(dtype=None)

In [ ]:
# create a tensor
x = torch.tensor([10.0,20.0,30.0,40.0,50.0])
x.dtype

torch.float32

In [ ]:
# Converting above tensor in float_16
x_float16 = x.type(dtype=torch.float16)

In [ ]:
x_float16

tensor([10., 20., 30., 40., 50.], dtype=torch.float16)

In [ ]:
# Converting x tensor to int
x_int8= x.type(torch.int8)
x_int8

tensor([10, 20, 30, 40, 50], dtype=torch.int8)

# Reshaping, stacking
#### torch.reshape(input, shape)====> Reshape the input into shape if compatible, can also use as torch.Tensor.reshape()
#### tensor.view() ===> Return the view of original tensor in different view, but share the same data as original tensor
#### torch.stack(tensors, dim=0)===> Concatenate a sequience of Tensor along with dimesion, all tensor must have same size

In [ ]:
# create a random tensor
a = torch.arange(4.)
print("Original tensor \n {}".format(a))
print("Chnaged shaped \n{}".format(torch.reshape(a,(2,2))))
b = torch.tensor([[10,20],
 [30,40]])
print(b)
print("Changed shape \n {}".format(torch.reshape(b,(-1,))))
c = torch.rand(5,8)
print(c)
print("Changed shaped in 4 X 10 \n {}".format(torch.reshape(c,(4,10))))
print("Changed chape in 2X20 \n {}".format(torch.reshape(c,(2,20))))




Original tensor 
 tensor([0., 1., 2., 3.])
Chnaged shaped 
tensor([[0., 1.],
        [2., 3.]])
tensor([[10, 20],
        [30, 40]])
Changed shape 
 tensor([10, 20, 30, 40])
tensor([[0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816],
        [0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600],
        [0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612, 0.1568, 0.2083],
        [0.3289, 0.1054, 0.9192, 0.4008, 0.9302, 0.6558, 0.0766, 0.8460],
        [0.3624, 0.3083, 0.0850, 0.0029, 0.6431, 0.3908, 0.6947, 0.0897]])
Changed shaped in 4 X 10 
 tensor([[0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998,
         0.5944],
        [0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014,
         0.3139],
        [0.4654, 0.1612, 0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008, 0.9302,
         0.6558],
        [0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029, 0.6431, 0.3908, 0.6947,
         0.0897]])
Changed chape in 2X20 
 tensor(

In [ ]:
x = torch.arange(1.,7.)
print("Shape of the tensor {}".format(x.shape))
print("Reshape the tensor in 2X3 is \n {}".format(torch.reshape(x,(2,3))))

Shape of the tensor torch.Size([6])
Reshape the tensor in 2X3 is 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# Understading view

x= torch.randn(4,4)
print("Size of Tensor {} \n".format(x.size()))
y = x.view(16)
print ("Reshape Tensor y is \n {}".format(y))
print("Size of Tensor y is {} \n".format(y.shape))
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print ("Reshape Tensor z is \n {}".format(z))
print("Shape of Tesnor z is {} \n".format(z.shape))


Size of Tensor torch.Size([4, 4]) 

Reshape Tensor y is 
 tensor([ 0.4788,  1.3537, -0.1593, -0.4249,  0.9442, -0.1849,  1.0608,  0.2083,
         1.3065,  0.4598,  0.2618, -0.7599, -2.0461, -1.5295,  0.4049,  0.6319])
Size of Tensor y is torch.Size([16]) 

Reshape Tensor z is 
 tensor([[ 0.4788,  1.3537, -0.1593, -0.4249,  0.9442, -0.1849,  1.0608,  0.2083],
        [ 1.3065,  0.4598,  0.2618, -0.7599, -2.0461, -1.5295,  0.4049,  0.6319]])
Shape of Tesnor z is torch.Size([2, 8]) 



In [ ]:
a = torch.randn(1,2,3,4)
print("Tensor a is \n {}".format(a))
print("Size of Tensor a is {} \n".format(a.size()))
# swape the 2 and 3 elements
b = a.transpose(2,3)
print("Afther swapping Tensor b is \n {}".format(b))
print("Size of Tensor b is {} \n".format(b.size()))
print("Check the Tensor a and b are equal or not {} \n".format(torch.equal(a,b)))
c = a.view(1,3,2,4)
print("Afther swapping Tensor c is \n {}".format(c))
print("Size of Tensor c is {} \n".format(c.size()))
print("Check whether Tensor b and c are equals or not {}\n".format(torch.equal(c,b)))
print("Check whether Tensor a and c are equals or not {}\n".format(torch.equal(c,a)))

Tensor a is 
 tensor([[[[-0.1483, -2.3184,  1.3032,  0.4879],
          [ 1.1340, -0.3556,  0.3618,  1.9993],
          [ 0.1787, -0.1293, -0.9291,  0.2762]],

         [[-0.5389,  0.4626, -0.8719, -0.0271],
          [ 0.3416, -0.2214,  1.2554, -0.7150],
          [ 0.8539,  0.5130,  0.5397,  0.5655]]]])
Size of Tensor a is torch.Size([1, 2, 3, 4]) 

Afther swapping Tensor b is 
 tensor([[[[-0.1483,  1.1340,  0.1787],
          [-2.3184, -0.3556, -0.1293],
          [ 1.3032,  0.3618, -0.9291],
          [ 0.4879,  1.9993,  0.2762]],

         [[-0.5389,  0.3416,  0.8539],
          [ 0.4626, -0.2214,  0.5130],
          [-0.8719,  1.2554,  0.5397],
          [-0.0271, -0.7150,  0.5655]]]])
Size of Tensor b is torch.Size([1, 2, 4, 3]) 

Check the Tensor a and b are equal or not False 

Afther swapping Tensor c is 
 tensor([[[[-0.1483, -2.3184,  1.3032,  0.4879],
          [ 1.1340, -0.3556,  0.3618,  1.9993]],

         [[ 0.1787, -0.1293, -0.9291,  0.2762],
          [-0.5389,  0.462

# Stack Squeex, Unsqueez and Permute

torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [ ]:
# Cretae a tensor
x = torch.arange(1.0,8)

In [ ]:
print (f"Tensor x is {x}")
print("Shape of tensor s is {} ".format(x.shape))

Tensor x is tensor([1., 2., 3., 4., 5., 6., 7.])
Shape of tensor s is torch.Size([7]) 


In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)

In [ ]:
print(x_stacked)
print(x_stacked.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])
torch.Size([4, 7])


In [ ]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [ ]:
# torch.squeez(tensor, dim =)
x = torch.zeros(2,1,2,1,2)
print("Orginal tensor x is \n {}".format(x))
print("Shape of tensor x is {} \n ".format(x.shape))

Orginal tensor x is 
 tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
Shape of tensor x is torch.Size([2, 1, 2, 1, 2]) 
 


In [ ]:
y = torch.squeeze(x)
print("Squeez tensor y is \n {}".format(y))
print("Shape of Squeez tensor is {}\n".format(y.shape))

Squeez tensor y is 
 tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
Shape of Squeez tensor is torch.Size([2, 2, 2])



In [ ]:
z = torch.squeeze(x,dim=1)
z, z.shape

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [ ]:
print(x.shape)
w = torch.squeeze(x, (1,3))
w, w.shape

torch.Size([2, 1, 2, 1, 2])


(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
## Unsqueezed
x = torch.randn([1,2,3,4])
x

tensor([[[[-0.7150, -0.0476,  0.5230,  0.9717],
          [-0.2779, -0.6116, -0.5572, -0.9683],
          [ 0.5716,  1.3596,  0.4334, -0.7172]],

         [[ 1.0554, -1.4534,  0.4652,  0.3714],
          [ 0.8800,  0.0561,  0.3782,  0.7051],
          [-1.7237, -0.8435,  0.4351,  0.2659]]]])

In [ ]:
y = torch.unsqueeze(x,dim=0)
y

tensor([[[[[-0.7150, -0.0476,  0.5230,  0.9717],
           [-0.2779, -0.6116, -0.5572, -0.9683],
           [ 0.5716,  1.3596,  0.4334, -0.7172]],

          [[ 1.0554, -1.4534,  0.4652,  0.3714],
           [ 0.8800,  0.0561,  0.3782,  0.7051],
           [-1.7237, -0.8435,  0.4351,  0.2659]]]]])

In [ ]:
y = torch.unsqueeze(x, dim=-1)
y, y.shape

(tensor([[[[[-0.7150],
            [-0.0476],
            [ 0.5230],
            [ 0.9717]],
 
           [[-0.2779],
            [-0.6116],
            [-0.5572],
            [-0.9683]],
 
           [[ 0.5716],
            [ 1.3596],
            [ 0.4334],
            [-0.7172]]],
 
 
          [[[ 1.0554],
            [-1.4534],
            [ 0.4652],
            [ 0.3714]],
 
           [[ 0.8800],
            [ 0.0561],
            [ 0.3782],
            [ 0.7051]],
 
           [[-1.7237],
            [-0.8435],
            [ 0.4351],
            [ 0.2659]]]]]),
 torch.Size([1, 2, 3, 4, 1]))

In [ ]:
x = torch.arange(1.0,8)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor {x_reshaped} \n")
print(f"Previous tensor shape {x_reshaped.shape} \n")
x_squeezed = torch.squeeze(x_reshaped)
print(f"New tensor is {x_squeezed} \n")
print(f"New tensor shape is {x_squeezed.shape}")

Previous tensor tensor([[1., 2., 3., 4., 5., 6., 7.]]) 

Previous tensor shape torch.Size([1, 7]) 

New tensor is tensor([1., 2., 3., 4., 5., 6., 7.]) 

New tensor shape is torch.Size([7])


In [ ]:
# We can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

# Create a tensor with specific shape
x_original = torch.rand(size=[224,224,3])
print("Before Permute shape is {} \n".format(x_original.shape))
x_permuted = torch.permute(x_original,(2,0,1))
print("After permure shape is {} \n".format(x_permuted.shape))

Before Permute shape is torch.Size([224, 224, 3]) 

After permure shape is torch.Size([3, 224, 224]) 



In [ ]:
x = torch.randn(size=[2,3,5])
print("Before permute tensor shape is {} \n".format(x.shape))
print("After permute tensor share is {} \n".format(torch.permute(x,dims=(1,0,2)).shape))

Before permute tensor shape is torch.Size([2, 3, 5]) 

After permute tensor share is torch.Size([3, 2, 5]) 



# Indexing (selecting data from tensors)

In [111]:
# Create a tensor

x = torch.arange(1,10).reshape([1,3,3])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [113]:
print ("x[0] {} \n".format(x[0]))

x[0] tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 



In [114]:
print("x[0][0] {} \n".format(x[0][0]))

x[0][0] tensor([1, 2, 3]) 



In [116]:
print("x[0][1] {} \n".format(x[0][1]))

x[0][1] tensor([4, 5, 6]) 



In [117]:
print(f"x[0][1][2] {x[0][1][2]} \n")

x[0][1][2] 6 



#### We can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [119]:
# Get all value of 0th dimension and 0th index of 1st dimension
print(x[:,0])

tensor([[1, 2, 3]])


In [120]:
# Get all 2nd value of 0th dimension and 1st dimension but 0th index of 1st dimension
print(x[:,0,1])

tensor([2])


In [124]:
# Get the all values of 0th and 1st dimesnion but only index 1 of 1st and 2nd dimesnion
print(x[:,:,1])

tensor([[2, 5, 8]])


In [122]:
# Get the all values 0the dimension but index 1 of 1st and 2nd dimension
print(x[:,1,1])

tensor([5])


In [125]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [ ]:
x

SyntaxError: invalid syntax (ipython-input-1863521418.py, line 3)

In [ ]:
#