# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor
random_tensor_A = torch.rand(size=[7,7])
print(random_tensor_A)



tensor([[0.1955, 0.6969, 0.6578, 0.9273, 0.7743, 0.0334, 0.4173],
        [0.9169, 0.3269, 0.3477, 0.5643, 0.2070, 0.9161, 0.2227],
        [0.6806, 0.8432, 0.4147, 0.6487, 0.3628, 0.0856, 0.2198],
        [0.7536, 0.2044, 0.1149, 0.8343, 0.2012, 0.2751, 0.4967],
        [0.6450, 0.4509, 0.0179, 0.8929, 0.8712, 0.7401, 0.0345],
        [0.9511, 0.7451, 0.7676, 0.7471, 0.6843, 0.2599, 0.7652],
        [0.2371, 0.6544, 0.1282, 0.7716, 0.7242, 0.4957, 0.2523]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_B = torch.rand(7,7)
print(random_tensor_B)

# Perform matrix multiplication
print(random_tensor_A.matmul(random_tensor_B))


tensor([[0.6548, 0.9490, 0.9561, 0.3473, 0.4789, 0.5905, 0.7808],
        [0.8349, 0.6641, 0.1942, 0.5527, 0.4171, 0.5989, 0.2189],
        [0.0432, 0.3744, 0.2581, 0.5984, 0.0638, 0.4104, 0.4151],
        [0.1213, 0.5541, 0.4366, 0.8091, 0.2811, 0.3961, 0.0529],
        [0.5613, 0.8362, 0.6683, 0.1503, 0.2853, 0.1770, 0.9153],
        [0.9973, 0.4716, 0.8285, 0.4051, 0.6054, 0.7822, 0.9203],
        [0.9651, 0.7194, 0.8518, 0.1045, 0.3317, 0.8965, 0.5016]])
tensor([[1.7214, 2.3719, 1.7975, 1.7705, 1.0665, 1.7074, 1.5761],
        [2.2015, 2.2953, 2.3632, 1.5892, 1.4437, 2.0562, 2.1059],
        [1.7474, 2.2224, 1.7054, 1.5876, 1.1146, 1.6622, 1.4436],
        [1.6369, 2.0114, 1.9396, 1.3120, 1.0766, 1.6411, 1.4115],
        [2.1682, 2.5153, 2.3235, 1.6407, 1.4571, 1.7759, 2.1529],
        [2.7504, 3.3440, 2.9028, 2.0941, 1.6316, 2.6292, 2.5132],
        [1.9450, 2.1559, 1.8333, 1.4810, 1.2019, 1.6322, 1.6680]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.random.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(7,7)
print(f"random tensor_A is : {random_tensor_A}\n")
torch.random.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(7,1)
print(f"random_tensor_B is : {random_tensor_B} \n")

# Matrix multiply tensors
print(f"randmon_tensor_A*randmon_tensor_B \n")
print(random_tensor_A.matmul(random_tensor_B))


random tensor_A is : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

random_tensor_B is : tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]]) 

randmon_tensor_A*randmon_tensor_B 

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# import torch
import torch
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
random_tensor_A = torch.rand(2,3).to(device=device)
print(f"random_tensor_A : {random_tensor_A} \n")
random_tensor_B = torch.rand(2,3).to(device=device)
print(f"randmon_tensor_B : {random_tensor_B} \n"})

IndentationError: unexpected indent (ipython-input-882002545.py, line 2)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
